[images]
  remote_images = [
    "https://i.pravatar.cc/**",
    "https://images.unsplash.com/**",
    "https://ext.same-assets.com/**"
  ]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
  command = "bun run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
